api = "0.2"

[buildpack]
  id = "onboarding/packit_buildpack"
  name = "Onboarding Packit Buildpack"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    dependency = "1.14.*"

  [[metadata.dependencies]]
    id = "dependency"
    name = "Needed Dependency"
    sha256 = "82a1b84f16858db03231eb201f90cce2a991078dda543879b87e738e2586854b"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://golang.org/dl/go1.14.5.linux-amd64.tar.gz"
    version = "1.14.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

